language: python
sudo: required
services:
  - docker
env:
  global:
    - DATABASE_HOST=postgres
    - DATABASE_NAME=postgres
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=postgres
before_install:
  - touch .env
  - docker-compose build
  - docker-compose run --rm web scripts/migrate_loaddata.sh
scripts:
 - scripts/test.sh
